spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calories
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: '/api/v1/docs'
    version: openapi_3_0
  swagger-ui:
    path: '/api/v1'
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
  group-configs:
    - group: products
      paths-to-match: /api/v1/products/**
    - group: dishes
      paths-to-match: /api/v1/dishes/**
    - group: users
      paths-to-match: /api/v1/users/**
    - group: other
      paths-to-exclude:
        - /api/v1/products/**
        - /api/v1/dishes/**
        - /api/v1/users/**
  cache:
    disabled: true
  override-with-generic-response: false

server:
  port: 3009
  forward-headers-strategy: framework

pgDump:
  path: 'D:/OSPanel/modules/database/PostgreSQL-14-Win10/bin/pg_dump.exe'
  database: 'calories'
  username: 'postgres'
  host: 'localhost'
  port: '5432'

task:
  cron:
    expression: "0 */30 * * * *"

mail:
  from: 'ykpon5@yandex.ru'
  password: 'apubohncvfzwsewn'
  to: 'a.cher.24top@gmail.com'
  debug: false
  smtp:
    host: smtp.yandex.ru
    port: 587
    auth: true
    starttls:
      enable: true

backup:
  directory: 'D:/backup'

zip:
  path: 'D:/7-Zip/7z.exe'