spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calories
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    locations: classpath:db/migration

server:
  port: 3009

backup:
  directory: D:/Backup

task:
  cron:
    expression: "0 * * * * ?"

mail:
  from:
  password:
  to:
  smtp:
    host: smtp.yandex.ru
    port: 587
    auth: true
    starttls:
      enable: true
